modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="sosiskisquad"
version="1.0.0"
displayName="SOSISKISQUAD"
displayURL="https://twitchworld.ru/"
credits="sosiskisquad"
authors="s0vakin"
displayTest="IGNORE_SERVER_VERSION"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.sosiskisquad]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration